version: '3.4'

services:
  worker:
    build:
      context: ../../.
      target: development
    volumes:
      - ../../:/usr/src/app
    environment:
      - DJANGO_CONFIGURATION=Dev
      - PSQL_HOST=postgres
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - postgres

  reactjs:
    build:
      context: ../../.
      target: frontend
    volumes:
      - ../../eventol/front/src:/app/src
      - ../../eventol/front/webpack-stats-local.json:/app/webpack-stats-local.json
    ports:
      - '3000:3000'

  redis:
    image: redis:4.0.2

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=eventol
      - POSTGRES_DB=eventol
    ports:
      - '5432:5432'
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
