version: "2"
services:
  worker:
    build: ../../.
    volumes:
      - ./src:/usr/src/app
    environment:
      - DJANGO_CONFIGURATION=Dev
  reactjs:
    build: ../../.
    restart: always
    volumes:
      - ./src:/usr/src/app
    working_dir: /usr/src/app/front
    command: npm start
    ports:
      - "3000:3000"
  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    volumes:
      - ./elk/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    expose:
      - "9300"
      - "9200"
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-dev
    ports:
      - "8000:80"
    depends_on:
      - worker
